version: '3'
services:
  whatsapp-service:
    restart: always
    build:
      context: ./
    volumes:
      - ./:/go/src/github.com/Deewai/chat-server
    container_name: chat-server
    ports:
      - "8080:8080"
    tty: true